### ISSUE TITLE
How is this related to vriteio/tiptap-solid or not

### ISSUE THREAD

**Issue by apatrida** [andi23rosca/tiptap-solid#2]
This is similar to https://github.com/vriteio/tiptap-solid
but isn't.

Is this one superceeding the other, or not related?

**Comment by andi23rosca** [comment]
They're unrelated, at the time I implemented this package there was no other library providing a `@tiptap/react`-like API for solid

If you're deciding which one to choose, I'd say pick the one you like the look of more 👍🏻

**Comment by apatrida** [comment]
they are almost identical but the other doesn't do the correct solid exports.
