### ISSUE TITLE
Cannot get NodeViewContent to work.

### ISSUE THREAD

**Issue by fominv** [andi23rosca/tiptap-solid#3]
Hi

Thank you for the awesome library. I was playing around and could not get the following to render Editable.

```
<solid-component count="5">
      <p>
        Editable
      </p>
</solid-component>
```

The examples in the readme do not show the usage `NodeViewContent`. It would be helpful to extend the counter example.

**Comment by andi23rosca** [comment]
Hi, I don't think I ever checked if the `NodeViewContent` actually works, I overlooked it when implementing the library.
I'll have to test it out and see if it needs any adjustments

**Comment by fominv** [comment]
~I am also still trying, if I find a solution I can also create a PR.~

Edit: Managed to get it working via https://github.com/andi23rosca/tiptap-solid/pull/4.

**Comment by andi23rosca** [comment]
Merged your PR, thanks!
Marking this as closed
